language: go
go:
  - 1.9.x
  - 1.10.x
  - tip

install:
    - pwd
    - export SOURCE=`pwd`
    - make prepare

cache:
    directories:
     - $GOPATH/src/qiniupkg.com

script:
    - make test

before_deploy:
    - make compile
    - ls $SOURCE/target/
deploy:
    provider: releases
    api_key: "$GITHUB_TOKEN"
    skip_cleanup: true
    file_glob: true
    file: $SOURCE/target/*
    overwrite: true
    on:
      tags: true

matrix:
  allow_failures:
    # qiniupkg
    - go: tip

